name: build

on: push

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Create Build directory
        run: mkdir build

      - name: Run cmake
        run: |
            cd build
            cmake ../

      - name: Build cmake
        run: cmake --build . --config RelWithDebInfo

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Create Build directory
        run: mkdir build

      - name: Run cmake
        run: |
            cd build
            cmake ../

      - name: Build cmake
        run: cmake --build . --config RelWithDebInfo
       
     
